# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_auto_20170206_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='facebook',
            field=models.URLField(blank=True, default='www.facebook.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='image_credit',
            field=models.CharField(blank=True, default='None', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='twitter',
            field=models.URLField(blank=True, default='www.twitter.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='website',
            field=models.URLField(blank=True, default='www.google.com'),
            preserve_default=False,
        ),
    ]
