# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_auto_20170206_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='description',
            field=models.TextField(default='Election'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='election',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
