# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0007_auto_20170206_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='name',
            field=models.CharField(default='Election', max_length=200),
            preserve_default=False,
        ),
    ]
