# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0009_auto_20170206_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='id',
        ),
        migrations.AlterField(
            model_name='election',
            name='year',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
