# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0012_auto_20170207_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='election_date',
            field=models.DateField(default='2017-03-04'),
            preserve_default=False,
        ),
    ]
