# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0014_auto_20170207_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='id',
            field=models.AutoField(auto_created=True, default='1', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='position_name',
            field=models.CharField(max_length=200),
        ),
    ]
