# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0015_auto_20170207_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='position_name',
            new_name='name',
        ),
    ]
