# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0019_position_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='votes_percentage',
            new_name='total_votes',
        ),
    ]
