# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0020_auto_20170208_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='positions_available',
        ),
    ]
