# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0021_remove_position_positions_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='positions_available',
        ),
        migrations.AddField(
            model_name='position',
            name='positions_available',
            field=models.PositiveSmallIntegerField(default='1'),
            preserve_default=False,
        ),
    ]
