# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0023_remove_candidate_race'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('major', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/%Y/candidates/')),
                ('image_credit', models.CharField(blank=True, max_length=200)),
                ('statement', models.TextField()),
                ('platform', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('submitted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Position')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateSubmissionAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
