# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0025_delete_candidatesubmissionadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatesubmission',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
