# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0026_candidatesubmission_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatesubmission',
            name='position',
        ),
        migrations.AddField(
            model_name='candidate',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CandidateSubmission',
        ),
    ]
