# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 21:25
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0027_auto_20170216_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/%Y/candidates/'),
        ),
    ]
