# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 23:29
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0029_position_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='platform',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='statement',
            field=tinymce.models.HTMLField(),
        ),
    ]
