# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0030_auto_20170218_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/%Y/candidates/'),
        ),
    ]
