# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 00:07
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0031_auto_20170218_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/%Y/candidates/'),
        ),
    ]
