# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0032_auto_20170218_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
