# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0033_auto_20170220_1117'),
    ]

    operations = [ 
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/candidates/'),
        ),
    ]
