# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0034_auto_20170224_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='platform',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='statement',
            field=models.TextField(),
        ),
    ]
